package KieRule;
import com.example.ItrackBackend.model.InwardTransaction;
import com.example.ItrackBackend.model.FlagFact;

rule "amount"

when
    transactionObject : InwardTransaction(dynamicParams.amount > 5000);
    flagFact : FlagFact();
then
    transactionObject.setChannelCode(50);
    flagFact.setFlag(false);
    update(flagFact);
end

rule "Compare Amount with Min Amount"
when
    $transaction: InwardTransaction($amount : amount)
    $profile: InwardProfile(min_amt : min_amt)
    eval($amount > min_amt)
then
    // Your consequences when the condition is true
    $transaction.setChannelCode(2);
    isTransactionFlagged = true; // Update the global flag if needed
end